version: "3.8"
services:
  sendir-rest:
    build:
      context: ./
      target: development
    container_name: sendir-rest
    hostname: sendir-rest
    environment:
      TZ: Asia/Tokyo
    restart: always
    volumes:
      - ./.go/pkg/:/go/pkg/
      - ./:/go/src/sendir-rest/
    ports:
      - 3001:3001
